### ISSUE TITLE
feature request: be able to use pattern matched in a request to load a file where it's path uses the pattern

### ISSUE THREAD

**Issue by radek1st** [azagniotov/stubby4j#49]
Hi, I'd like to be able to choose a file that gets served in the response based on the regex in the request url. Currently, it is only possible to replace the pattern inside of a file, but not the path to the file. Something like in the below example:

-  request:
      method: [GET]
      url: ^/category/([a-zA-Z]+)

   response:
      status: 200
      file: /path/to/my/files/<% url.1 %>

**Comment by azagniotov** [comment]
Thanks for suggesting this. My next 3-4 weeks are pretty busy, so I am not sure when I can look into this

**Comment by radek1st** [comment]
I might have some time now, so I can have a look. Any suggestions on how to approach it?

**Comment by azagniotov** [comment]
Sure. From a high level:
When stubby parses the YAML config, everything gets loaded into memory. In other words the contents from the `file` path would be pre-loaded, instead of served on demand.

Have a look at `YamlParser` class that does the YAML parsing. Specifically have a look at: https://github.com/azagniotov/stubby4j/blob/master/main/java/by/stub/yaml/YamlParser.java#L153

Maybe a good approach would be to start (without looking deeply at the code at this stage) during YAML parsing: If `file` relative URI contains  `<% url.1 %>` token - do not preload contents from that `file` during YAML parsing (frankly, you cannot preload anyway, since the URI contains regex token). 

So, if stubbed request was matched, extract the value for the regex token, build a valid URI using the `file` in response and serve the response based on the regex.

The matching of stubbed request starts to happen in `StubbedDataManager`:
https://github.com/azagniotov/stubby4j/blob/master/main/java/by/stub/database/StubbedDataManager.java#L105 , because `equals()` of `StubHttpLifecycle` uses `StubRequest` to determine equality:
https://github.com/azagniotov/stubby4j/blob/master/main/java/by/stub/yaml/stubs/StubHttpLifecycle.java#L187
https://github.com/azagniotov/stubby4j/blob/master/main/java/by/stub/yaml/stubs/StubRequest.java#L225

I hope i was clear!
