### ISSUE TITLE
unable to read post data when run with `--debug`

### ISSUE THREAD

**Issue by munkyboy** [azagniotov/stubby4j#55]
given the endpoint:

    - request:
        method: [POST]
        url: /foo
        post: "^qqq=123$"

running with `--debug` causes this error: 

     POST [stubs]/foo: Error when extracting POST body: java.util.NoSuchElementException, returning null..

In debug mode, the raw HTTP request is parsed and dumped to stdout. Later, the code reads the request input stream to process the post body and the stream has already been drained to perform the previous dump.

The error occurs in the `extractPostRequestBody` method of `main/java/by/stub/utils/HandlerUtils.java`

**Comment by azagniotov** [comment]
@munkyboy Thank you for that. I apologize for the late reply. I will look into this

**Comment by azagniotov** [comment]
Interestingly, it is not because of `extractPostRequestBody`:

When dumping raw `HttpServletRequest` to console during `--debug`, I am calling `request.getParameterNames()`. Jetty's `Request` implementing the `HttpServletRequest` would eventually call the `request.getInputStream()` without me realizing

**Comment by azagniotov** [comment]
Fixed in v4.0.0
