### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by asarkar** [azagniotov/stubby4j#85]
I need to report on request method, URL and response status. Dropwizard has a [metrics library](http://metrics.dropwizard.io/3.1.0/manual/jetty/) for Jetty, but I don't see how to use it with Stubby4J since it is not designed for extension and is a very closed system. For example, class `JettyFactory`; by definition, and as per factory design pattern, a factory can produce multiple types of the same "thing". If there's no way to create a different instance of Jetty other than the default from a "factory", the name is rather misleading. The `stubby4j-x.x.x-no-jetty.jar` still has the Jetty related classes from package `server` in it, so it's not possible to easily plugin in an instrumented Jetty.

**Comment by azagniotov** [comment]
@asarkar As per documentation, the `stubby4j-x.x.x-no-jetty.jar` artifact is  an uber-ish JAR containing all the 3rd-party deps except Jetty. The idea here is that the consumer of the library will provide Jetty dependencies on the classpath. 

Regarding `JettyFactory`, I respectfully disagree that the name misleading. A `factory` does not always mean that it produce multiple types of the same `thing`. Sometimes a factory has only one way to create an object. In case of `JettyFactory`, up until now there was never a need to create a `org.eclipse.jetty.server.Server` using multiple ways. 

Regarding metrics: yes, I never planned to instrument metrics for stubby4j. Which may or may not been an educated decision. The main reason why I never considered it is because up until now no one asked for this.

**Comment by asarkar** [comment]
I think it'd make sense to separate the "server" from the "request matching" by splitting the project into separate modules, something like the following:
```
stubby4j
--- core
--- server-api
--- jetty-server
```

Of course, the names are just something I came up with.  This way, the uber jar could simply scoop up all of the above modules, while someone looking for additional features could implement the `server-api` with, say, `jetty-server-instrumented`. Optionally, all of this can further be simplified by using dependency injection; no additional framework is necessary, because the Java SE has support for CDI.
